{% set version = "1.1.0" %}

package:
  name: descartes
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/descartes/descartes-{{ version }}.tar.gz
  sha256: 135a502146af5ed6ff359975e2ebc5fa4b71b5432c355c2cafdc6dea1337035b

build:
  number: 5
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - descartes

about:
  home: http://bitbucket.org/sgillies/descartes/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Use geometric objects as matplotlib paths and patches'

extra:
  recipe-maintainers:
    - ocefpaf
