{% set version = "1.1.0" %}

package:
  name: descartes
  version: {{ version }}

source:
  fn: descartes-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/descartes/descartes-{{ version }}.tar.gz
  sha256: 135a502146af5ed6ff359975e2ebc5fa4b71b5432c355c2cafdc6dea1337035b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib

test:
  imports:
    - descartes

about:
  home: http://bitbucket.org/sgillies/descartes/
  license: BSD
  summary: 'Use geometric objects as matplotlib paths and patches.'

extra:
  recipe-maintainers:
    - ocefpaf
