travis:
  secure:
    BINSTAR_TOKEN: s1W/cUNk7WIL2/m8MCsfeihQjfAmFl+RYaZtpQ6BY07R75S0gYkhedjXT4q2sOHSiu/RQ8i9W3DCCyniGL4cbuEgMaY1eDv8LS5EVhmPp18tZE5kxGuwRT6NvOY1KaUNfgiV9MomoRz0gJHGuj9tGUzLGsnUUwAvJ9Bg8+yNnk+DljS/vQ1a1/+RMZWXLWaaXHLySRJKx/jeTes/OP4ylig0PL/UzY3BXhF/tiaJ+O/kxhiJI/4s1McjwQk0dg9bwF042aYksY7lhyVBznknpsOPsV13IOXdQuSPAMlEYogQaKRR9EGRDOz3YpCvEojifFoH/fUe2tCMp/PComLj9UP5PmNiOXT81J6jUyKtXIf0ErL4Vhq0pGaK+N3n5JHqUCnV8J+3wcE/MZLhRX/lInaqO2Zk9kE4aDsm5QB8HsP9n6xEC7r7/jOSG8qufXw+TgVMWyiCO54KU3jYBQi8pw+xB7mV67QHGKSg+x55WFPhDPVxnBaFVlxz3iAfEhE1RHGBK9NIDQBcjXq3HXfbl8rBy8n4weEMslmOIq7GBeYL0ZM74C3uDqPm4PTDMxNtCGSHQ4hBFhGHo0boDPWFhN9ZorRESZUiU7V0yZ0uKfsRdblbS18tZleIPFhs8I/qnMUBddlnoL6Sm1fDbINAg/r9PghJseor/pTp0HAClyw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
